import{a as v,i as h,S as B}from"./assets/vendor-64b55ca9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const F="https://pixabay.com/api/",C="42459298-1821cc9c9c9d24f5ec127ca7c",f=async(r,t=1,s=15)=>{const n=`${F}?key=${C}&q=${r}&image-type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=${s}`;try{const e=await v.get(n);return(!e.data.hits||e.data.hits.length===0)&&h.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#FAFAFB",backgroundColor:"#EF4040",iconColor:"#FAFAFB",position:"topRight",theme:"dark"}),e.data.totalHits&&t*s>e.data.totalHits?(h.info({message:"We're sorry, but you've reached the end of search results.",messageColor:"#2E2F42",position:"topRight",theme:"light"}),[]):e.data.hits}catch(e){throw console.error("Error fetching data:",e),new Error("Image error!")}},m=(r,t)=>{if(r.length>0){const s=r.map(({largeImageURL:e,webformatURL:o,tags:i,likes:w,views:L,comments:E,downloads:$})=>`<li class="gallery-item">
                         <a class="link" href="${e}">
                            <img
                            class="gallery-image"
                            src="${o}"
                            alt="${i}"
                            data-source="${e}"/>
                        <div class="desc">
                            <p class="likes">Likes ${w}</p>
                            <p class="views">Views ${L}</p>
                            <p class="comments">Comments ${E}</p>
                            <p class="downloads">Downloads ${$}</p>
                        </div>
                        </a>
                    </li>`).join("");t.insertAdjacentHTML("beforeend",s),new B(".gallery-item a").refresh()}else console.log("No images found. Please try a different search query.")},P=document.getElementById("search-form"),q=document.querySelector(".searchInput"),a=document.querySelector(".image-gallery"),u=document.querySelector(".load-more-btn"),c=document.createElement("span");c.classList.add("loader");let l=1,g="";function S(){a.innerHTML=""}function y(){u.style.display="block"}function p(){u.style.display="none"}function b(){c.style.display="block"}function d(){c.style.display="none"}d();p();function A(){l=1}P.addEventListener("submit",async function(r){r.preventDefault();const t=q.value.trim();if(g=t,a.before(c),!t){console.log("Please enter a search query before submitting.");return}S(),A(),d();try{b();const s=await f(t,l);m(s,a);const n=a.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:2*n,behavior:"smooth"}),y()}catch(s){console.error("Error:",s)}finally{d()}});async function M(){l++,u.before(c),b(),p();try{const r=await f(g,l);m(r,a);const t=a.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:2*t,behavior:"smooth"})}catch(r){console.error("Error:",r)}finally{d(),y()}}u.addEventListener("click",M);
//# sourceMappingURL=commonHelpers.js.map
