import{a as P,i as m,S as B}from"./assets/vendor-64b55ca9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const C="https://pixabay.com/api/",S="42459298-1821cc9c9c9d24f5ec127ca7c",l=15,g=async(r,t=1)=>{const s=`${C}?key=${S}&q=${r}&image-type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=${l}`;try{const n=await P.get(s);return(!n.data.hits||n.data.hits.length===0)&&m.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#FAFAFB",backgroundColor:"#EF4040",iconColor:"#FAFAFB",position:"topRight",theme:"dark"}),n.data.totalHits&&t*l>n.data.totalHits?(m.info({message:"We're sorry, but you've reached the end of search results.",messageColor:"#2E2F42",position:"topRight",theme:"light"}),[]):n.data.hits}catch(n){throw console.error("Error fetching data:",n),new Error("Image error!")}},p=(r,t)=>{if(r.length>0){const s=r.map(({largeImageURL:e,webformatURL:o,tags:a,likes:w,views:$,comments:v,downloads:F})=>`<li class="gallery-item">
                         <a class="link" href="${e}">
                            <img
                            class="gallery-image"
                            src="${o}"
                            alt="${a}"
                            data-source="${e}"/>
                        <div class="desc">
                            <p class="likes">Likes ${w}</p>
                            <p class="views">Views ${$}</p>
                            <p class="comments">Comments ${v}</p>
                            <p class="downloads">Downloads ${F}</p>
                        </div>
                        </a>
                    </li>`).join("");t.insertAdjacentHTML("beforeend",s),new B(".gallery-item a").refresh()}else console.log("Error")},q=document.getElementById("search-form"),A=document.querySelector(".searchInput"),i=document.querySelector(".image-gallery"),h=document.querySelector(".load-more-btn"),c=document.createElement("span");c.classList.add("loader");let d=1,y="";function M(){i.innerHTML=""}function b(){h.style.display="block"}function u(){h.style.display="none"}function L(){c.style.display="block"}function f(){c.style.display="none"}f();u();function H(){d=1}function E(r){const t=i.firstElementChild;if(t){const s=t.getBoundingClientRect().height;window.scrollBy({top:r*s,behavior:"smooth"})}}q.addEventListener("submit",async function(r){r.preventDefault();const t=A.value.trim();if(y=t,i.before(c),!t){console.log("Please enter a search query before submitting.");return}M(),H(),f();try{L();const s=await g(t,d);if(s.length===0){u();return}p(s,i),E(2),b()}catch(s){console.error("Error:",s)}finally{f()}});async function I(){let r;d+=1,h.before(c),L(),u();try{r=await g(y,d,l),p(r,i),E(2)}catch(t){console.error("Error:",t)}finally{f(),r.length<l?u():b()}}h.addEventListener("click",I);
//# sourceMappingURL=commonHelpers.js.map
