import{a as F,i as h,S as B}from"./assets/vendor-64b55ca9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const C="https://pixabay.com/api/",P="42459298-1821cc9c9c9d24f5ec127ca7c",m=async(r,t=1,o=15)=>{const n=`${C}?key=${P}&q=${r}&image-type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=${o}`;try{const e=await F.get(n);return(!e.data.hits||e.data.hits.length===0)&&h.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#FAFAFB",backgroundColor:"#EF4040",iconColor:"#FAFAFB",position:"topRight",theme:"dark"}),e.data.totalHits&&t*o>e.data.totalHits?(h.info({message:"We're sorry, but you've reached the end of search results.",messageColor:"#2E2F42",position:"topRight",theme:"light"}),[]):e.data.hits}catch(e){throw console.error("Error fetching data:",e),new Error("Image error!")}},y=(r,t)=>{if(r.length>0){const o=r.map(({largeImageURL:e,webformatURL:s,tags:a,likes:w,views:E,comments:$,downloads:v})=>`<li class="gallery-item">
                         <a class="link" href="${e}">
                            <img
                            class="gallery-image"
                            src="${s}"
                            alt="${a}"
                            data-source="${e}"/>
                        <div class="desc">
                            <p class="likes">Likes ${w}</p>
                            <p class="views">Views ${E}</p>
                            <p class="comments">Comments ${$}</p>
                            <p class="downloads">Downloads ${v}</p>
                        </div>
                        </a>
                    </li>`).join("");t.insertAdjacentHTML("beforeend",o),new B(".gallery-item a").refresh()}else console.log("No images found. Please try a different search query.")},q=document.getElementById("search-form"),S=document.querySelector(".searchInput"),i=document.querySelector(".image-gallery"),u=document.querySelector(".load-more-btn"),c=document.createElement("span");c.classList.add("loader");let l=1,g="";function A(){i.innerHTML=""}function p(){u.style.display="block"}function f(){u.style.display="none"}function b(){c.style.display="block"}function d(){c.style.display="none"}d();f();function M(){l=1}function L(r){const t=i.firstElementChild;if(t){const o=t.getBoundingClientRect().height;window.scrollBy({top:r*o,behavior:"smooth"})}}q.addEventListener("submit",async function(r){r.preventDefault();const t=S.value.trim();if(g=t,i.before(c),!t){console.log("Please enter a search query before submitting.");return}A(),M(),d();try{b();const o=await m(t,l);if(o.length===0){f();return}y(o,i),L(2),p()}catch(o){console.error("Error:",o)}finally{d()}});async function H(){l++,u.before(c),b(),f();try{const r=await m(g,l);y(r,i),L(2)}catch(r){console.error("Error:",r)}finally{d(),p()}}u.addEventListener("click",H);
//# sourceMappingURL=commonHelpers.js.map
